trigger:
  branches:
    include:
      - main  # branch để kích hoạt CI/CD

pool:
  vmImage: 'ubuntu-latest'  # Chọn máy ảo Ubuntu

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Phiên bản Node.js bạn cần

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build application'

- script: |
    npm test
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  inputs:
    Pathtopublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
